INSERT INTO DW.sale_indicator_dim (
    sale_indicator_key,
    payment_sequential,
    payment_type,
    payment_installments,
    order_status
)
SELECT
    UUID() AS sale_indicator_key,
    seq.seq,
    pt.payment_type,
    inst.installments,
    os.order_status
FROM
    (SELECT 1 AS seq UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION
     SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10 UNION
     SELECT 11 UNION SELECT 12 UNION SELECT 13 UNION SELECT 14 UNION SELECT 15 UNION
     SELECT 16 UNION SELECT 17 UNION SELECT 18 UNION SELECT 19 UNION SELECT 20 UNION
     SELECT 21 UNION SELECT 22 UNION SELECT 23 UNION SELECT 24 UNION SELECT 25 UNION
     SELECT 26 UNION SELECT 27 UNION SELECT 28 UNION SELECT 29) AS seq
        JOIN
    (SELECT 0 AS installments UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION
     SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION
     SELECT 10 UNION SELECT 11 UNION SELECT 12 UNION SELECT 13 UNION SELECT 14 UNION
     SELECT 15 UNION SELECT 16 UNION SELECT 17 UNION SELECT 18 UNION SELECT 19 UNION
     SELECT 20 UNION SELECT 21 UNION SELECT 22 UNION SELECT 23 UNION SELECT 24) AS inst
        JOIN
    (SELECT 'boleto' AS payment_type UNION
     SELECT 'credit_card' UNION
     SELECT 'debit_card' UNION
     SELECT 'not_defined' UNION
     SELECT 'voucher') AS pt
        JOIN
    (SELECT 'approved' AS order_status UNION
     SELECT 'canceled' UNION
     SELECT 'created' UNION
     SELECT 'delivered' UNION
     SELECT 'invoiced' UNION
     SELECT 'processing' UNION
     SELECT 'shipped' UNION
     SELECT 'unavailable') AS os;